
#ifndef CLAIMRPCDEFS_H

 // always keep defines T_ + value in upper case
 #define T_NORMALIZEDNAME                "normalizedName"
 #define T_BLOCKHASH                     "blockhash"
 #define T_CLAIMS                        "claims"
 #define T_CLAIMID                       "claimId"
 #define T_TXID                          "txId"
 #define T_N                             "n"
 #define T_AMOUNT                        "amount"
 #define T_HEIGHT                        "height"
 #define T_VALUE                         "value"
 #define T_NAME                          "name"
 #define T_VALIDATHEIGHT                 "validAtHeight"
 #define T_NAMES                         "names"
 #define T_EFFECTIVEAMOUNT               "effectiveAmount"
 #define T_LASTTAKEOVERHEIGHT            "lastTakeoverHeight"
 #define T_ORIGINALHEIGHT                "originalHeight"
 #define T_SUPPORTS                      "supports"
 #define T_SUPPORTSWITHOUTCLAIM          "supportsWithoutClaim"
 #define T_TOTALNAMES                    "totalNames"
 #define T_TOTALCLAIMS                   "totalClaims"
 #define T_TOTALVALUE                    "totalValue"
 #define T_CONTROLLINGONLY               "controllingOnly"
 #define T_CLAIMTYPE                     "claimType"
 #define T_DEPTH                         "depth"
 #define T_INCLAIMTRIE                   "inClaimTrie"
 #define T_ISCONTROLLING                 "isControlling"
 #define T_INSUPPORTMAP                  "inSupportMap"
 #define T_INQUEUE                       "inQueue"
 #define T_BLOCKSTOVALID                 "blocksToValid"
 #define T_NODES                         "nodes"
 #define T_CHILDREN                      "children"
 #define T_CHARACTER                     "character"
 #define T_NODEHASH                      "nodeHash"
 #define T_VALUEHASH                     "valueHash"
 #define T_PAIRS                         "pairs"
 #define T_ODD                           "odd"
 #define T_HASH                          "hash"
 #define T_BID                           "bid"
 #define T_SEQUENCE                      "sequence"
 #define T_CLAIMSADDEDORUPDATED          "claimsAddedOrUpdated"
 #define T_SUPPORTSADDEDORUPDATED        "supportsAddedOrUpdated"
 #define T_CLAIMSREMOVED                 "claimsRemoved"
 #define T_SUPPORTSREMOVED               "supportsRemoved"
 #define T_ADDRESS                       "address"
 #define T_PENDINGAMOUNT                 "pendingAmount"

#endif // CLAIMRPCDEFS_H
