.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. lbrycrd_qt test_lbrycrd_qt
clean: FORCE
	$(MAKE) -C .. lbrycrd_qt_clean test_lbrycrd_qt_clean
check: FORCE
	$(MAKE) -C .. test_lbrycrd_qt_check
lbrycrd-qt lbrycrd-qt.exe: FORCE
	 $(MAKE) -C .. lbrycrd_qt
